### ISSUE TITLE
Crashing when opening any world or server

### ISSUE THREAD

**Issue by minglsc** [CIOCOLATA47/AntiAfk#7]
The mod causes the game to crash when attempting to open any world or server and even creating new worlds. Crashes after "loading world" is 100% complete. This message displays in the launcher after crash:

The game crashed whilst ticking player
Error: java.lang.NullPointerException: Cannot read field "field_6012" because "player" is null

I believe the crashes started because I exited an online server without deactivating the AntiAfk jumping (I disconnected without pressing my hotkey a second time to turn it off). I've pasted the crash report below. 

```

---- Minecraft Crash Report ----
// You're mean.

Time: 2024-06-10 18:46:22
Description: Ticking player

java.lang.NullPointerException: Cannot read field "field_6012" because "player" is null
	at net.minecraft.class_1657.handler$zza000$antiafk$onTick(class_1657.java:2403)
	at net.minecraft.class_1657.method_5773(class_1657.java)
	at net.minecraft.class_3222.method_14226(class_3222.java:586)
	at net.minecraft.class_3244.method_18784(class_3244.java:267)
	at net.minecraft.class_2535.method_10754(class_2535.java:393)
	at net.minecraft.class_3242.method_14357(class_3242.java:176)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1009)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:889)
	at net.minecraft.class_1132.method_3748(class_1132.java:113)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:691)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:275)
	at java.base/java.lang.Thread.run(Thread.java:1583)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_1657.handler$zza000$antiafk$onTick(class_1657.java:2403)
	at net.minecraft.class_1657.method_5773(class_1657.java)

-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 39
	Entity Name: m_i_n_g
	Entity's Exact location: 2.50, 66.00, 23.50
	Entity's Block location: World: (2,66,23), Section: (at 2,2,7 in 0,4,1; chunk contains blocks 0,-64,16 to 15,319,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_3222.method_14226(class_3222.java:586)
	at net.minecraft.class_3244.method_18784(class_3244.java:267)
	at net.minecraft.class_2535.method_10754(class_2535.java:393)
	at net.minecraft.class_3242.method_14357(class_3242.java:176)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1009)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:889)
	at net.minecraft.class_1132.method_3748(class_1132.java:113)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:691)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:275)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- System Details --
Details:
	Minecraft Version: 1.20.6
	Minecraft Version ID: 1.20.6
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 544198976 bytes (518 MiB) / 973078528 bytes (928 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 5900HX with Radeon Graphics        
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.29
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc.
	Graphics card #0 VRAM (MB): 512.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.21912.14
	Graphics card #1 name: NVIDIA GeForce RTX 3080 Laptop GPU
	Graphics card #1 vendor: NVIDIA
	Graphics card #1 VRAM (MB): 8192.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 31.0.15.5244
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 25007.00
	Virtual memory used (MB): 14556.64
	Swap memory total (MB): 9216.00
	Swap memory used (MB): 129.40
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		antiafk: AntiAfk 1.1.3-1.20.6
		fabric-api: Fabric API 0.98.0+1.20.6
			fabric-api-base: Fabric API Base 0.4.40+80f8cf51b0
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.59+e9d2a72bb0
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.25+be5d88beb0
			fabric-block-api-v1: Fabric Block API (v1) 1.0.20+6dfe4c9bb0
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.8+80f8cf51b0
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.50+80f8cf51b0
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.12+7f945d5bb0
			fabric-command-api-v1: Fabric Command API (v1) 1.2.45+f71b366fb0
			fabric-command-api-v2: Fabric Command API (v2) 2.2.24+80f8cf51b0
			fabric-commands-v0: Fabric Commands (v0) 0.2.62+df3654b3b0
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.5+b82b2392b0
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.4+7f945d5bb0
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.1.0+70fd1b46b0
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.27+80f8cf51b0
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.16+2a2c66b6b0
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 19.1.0+ad474493b0
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.68+94793913b0
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.8+e9d2a72bb0
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.6+c5fc38b3b0
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.50+80f8cf51b0
			fabric-item-api-v1: Fabric Item API (v1) 8.2.0+5bcea88ab0
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.39+aae0949ab0
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.45+80f8cf51b0
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.43+df3654b3b0
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.4+c5fc38b3b0
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.5+97f703dab0
			fabric-message-api-v1: Fabric Message API (v1) 6.0.10+109a837cb0
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.12+80f8cf51b0
			fabric-models-v0: Fabric Models (v0) 0.4.11+9386d8a7b0
			fabric-networking-api-v1: Fabric Networking API (v1) 4.0.8+0dca0349b0
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.4+c5fc38b3b0
			fabric-particles-v1: Fabric Particles (v1) 4.0.0+c5fc38b3b0
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.3+c5fc38b3b0
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.16+ad474493b0
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.12+97f703dab0
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.12+80f8cf51b0
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.61+df3654b3b0
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.46+73761d2eb0
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.3+2c869dedb0
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.64+df3654b3b0
			fabric-rendering-v1: Fabric Rendering (v1) 4.2.4+b21c00cbb0
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.1.0+83154f1bb0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.1.0+c0e5481fb0
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.21+7b70ea8ab0
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.73+8c7b71c2b0
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.21+c5fc38b3b0
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.6+c5fc38b3b0
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.10+74e2f560b0
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		java: OpenJDK 64-Bit Server VM 21
		litematica: Litematica 0.17.999-sakura.5
		lithium: Lithium 0.12.3
		malilib: MaLiLib 0.18.999-sakura.4
		minecraft: Minecraft 1.20.6
		sodium: Sodium 0.5.8+mc1.20.6
		worldedit: WorldEdit 7.3.1+6763-2e55f4f
		xaerominimap: Xaero's Minimap 24.1.4
	Server Running: true
	Player Count: 1 / 8; [class_3222['m_i_n_g'/39, l='ServerLevel[Testing World]', x=2.50, y=66.00, z=23.50]]
	Active Data Packs: vanilla, fabric, fabric-convention-tags-v2
	Available Data Packs: bundle, fabric, fabric-convention-tags-v2, trade_rebalance, update_1_21, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: -843312522611910994
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.15.11-1.20.6
```

**Comment by minglsc** [comment]
After uninstalling and reinstalling the mod, I am still unable to join any world or server when AntiAfk is in my mods folder.

**Comment by CIOCOLATA47** [comment]
[antiafk.zip](https://github.com/user-attachments/files/15786554/antiafk.zip)
It should be fixed now try it out and let me know
